// AUTO-GENERATED by scripts/install-plugins.ts — DO NOT EDIT
// Last generated: 2026-03-30T22:58:18.540Z
// @ts-nocheck
import type { TisanePlugin, TisaneTheme } from "tisane"

export const pluginComponents: TisanePlugin["components"] = []
export const pluginCategories: NonNullable<TisanePlugin["categories"]> = []
export const pluginMap: Record<string, TisanePlugin> = {}
export const themeMap: Record<string, TisaneTheme> = {}
